# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MKVideoManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
platform :ios, '10.0'
	use_frameworks!
	inhibit_all_warnings!

  # Pods for MKVideoManager
  pod 'SnapKit'
  pod 'Hero'
  pod 'GPUImage'
#pod 'GPUImage', :git => 'https://github.com/holla-world/GPUImage.git', :tag => '0.1.73'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
	pod 'Giphy'
	pod 'AMPopTip'
end
