# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MKVideoManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MKVideoManager
  pod 'SnapKit', '~> 4.0.0'
  pod 'Hero'
#  pod 'GPUImage'
pod 'GPUImage', :git => 'https://github.com/holla-world/GPUImage.git', :tag => '0.1.73'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
end
